[build]
  command = "composer install --no-dev --optimize-autoloader && npm run prod"
  publish = "public"

[build.environment]
  PHP_VERSION = "8.1"  # Tentukan versi PHP yang ingin digunakan

[[redirects]]
  from = "/"
  to = "/index.php"
  status = 200
